version: '3'
services:
  app:
    container_name: cycleapp
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
  mongo:
    container_name: cyclemongo
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb: